spring.application.name=EmployeeManagementSystem

spring.datasource.url=${data_base_url}
spring.datasource.username=${data_base_name}

spring.datasource.password=${data_base_pass}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true